In [111]:
# numpy

In [112]:
import numpy as np

a = np.array([1,2,3,4], 'uint8')
for elem in  np.sctypeDict:
    print(elem)

?
0
byte
b
1
ubyte
B
2
short
h
3
ushort
H
4
i
5
uint
I
6
intp
p
9
uintp
P
10
long
l
7
ulong
L
8
longlong
q
ulonglong
Q
half
e
23
f
11
double
d
12
longdouble
g
13
cfloat
F
14
cdouble
D
15
clongdouble
G
16
O
17
S
18
unicode
U
19
void
V
20
M
21
m
22
b1
bool8
i8
int64
u8
uint64
f2
float16
f4
float32
f8
float64
c8
complex64
c16
complex128
object0
bytes0
str0
void0
M8
datetime64
m8
timedelta64
int32
i4
uint32
u4
int16
i2
uint16
u2
int8
i1
uint8
u1
complex_
single
csingle
singlecomplex
float_
intc
uintc
int_
longfloat
clongfloat
longcomplex
bool_
bytes_
string_
str_
unicode_
object_
int
float
complex
bool
object
str
bytes
a
int0
uint0


In [113]:
np.complex64(a)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j], dtype=complex64)

In [114]:
np.array([x for x in range(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
np.eye(3,4) # тут используются размерности 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [116]:
np.ones([3,2]) # тут используется shape

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [117]:
np.full([2,3,2], -1)

array([[[-1, -1],
        [-1, -1],
        [-1, -1]],

       [[-1, -1],
        [-1, -1],
        [-1, -1]]])

In [118]:
np.diag([1,2,3,4,5,6,7,8,1,11,11])

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 11,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11]])

In [119]:
np.arange(3,12,1.2)

array([ 3. ,  4.2,  5.4,  6.6,  7.8,  9. , 10.2, 11.4])

In [120]:
np.linspace(10, 1000, 5)

array([  10. ,  257.5,  505. ,  752.5, 1000. ])

In [121]:
np.logspace(0, 1, 5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [122]:
np. geomspace(10,1000,5)

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

In [123]:
np.array([(x,y) for x in range(1, 4, 2) for y in range (1, 5, 3)])

array([[1, 1],
       [1, 4],
       [3, 1],
       [3, 4]])

In [124]:
a = np.array([ x for x in range(10)])
a.shape = 2 ,5 
b = a.reshape(10)
a[0][1] = 100
print(a)
print(b)

[[  0 100   2   3   4]
 [  5   6   7   8   9]]
[  0 100   2   3   4   5   6   7   8   9]


In [125]:
print(a.reshape(-1, 1))

[[  0]
 [100]
 [  2]
 [  3]
 [  4]
 [  5]
 [  6]
 [  7]
 [  8]
 [  9]]


In [126]:

a.resize(4,5, refcheck = True)
print(a)


ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [127]:
b = a.T

In [128]:
print(b)

[[  0   5]
 [100   6]
 [  2   7]
 [  3   8]
 [  4   9]]


In [129]:

a = np.array([[x,y] for x in np.arange(1,3,0.5) for y in np.arange(2,4,0.5)])
print(a)
b = np.array([[x,y] for x in np.arange(-1,1,0.5) for y in np.arange(1,2,0.25)])
print(b)

[[1.  2. ]
 [1.  2.5]
 [1.  3. ]
 [1.  3.5]
 [1.5 2. ]
 [1.5 2.5]
 [1.5 3. ]
 [1.5 3.5]
 [2.  2. ]
 [2.  2.5]
 [2.  3. ]
 [2.  3.5]
 [2.5 2. ]
 [2.5 2.5]
 [2.5 3. ]
 [2.5 3.5]]
[[-1.    1.  ]
 [-1.    1.25]
 [-1.    1.5 ]
 [-1.    1.75]
 [-0.5   1.  ]
 [-0.5   1.25]
 [-0.5   1.5 ]
 [-0.5   1.75]
 [ 0.    1.  ]
 [ 0.    1.25]
 [ 0.    1.5 ]
 [ 0.    1.75]
 [ 0.5   1.  ]
 [ 0.5   1.25]
 [ 0.5   1.5 ]
 [ 0.5   1.75]]


In [130]:
ab = np.hstack([a,b])
print(ab)

[[ 1.    2.   -1.    1.  ]
 [ 1.    2.5  -1.    1.25]
 [ 1.    3.   -1.    1.5 ]
 [ 1.    3.5  -1.    1.75]
 [ 1.5   2.   -0.5   1.  ]
 [ 1.5   2.5  -0.5   1.25]
 [ 1.5   3.   -0.5   1.5 ]
 [ 1.5   3.5  -0.5   1.75]
 [ 2.    2.    0.    1.  ]
 [ 2.    2.5   0.    1.25]
 [ 2.    3.    0.    1.5 ]
 [ 2.    3.5   0.    1.75]
 [ 2.5   2.    0.5   1.  ]
 [ 2.5   2.5   0.5   1.25]
 [ 2.5   3.    0.5   1.5 ]
 [ 2.5   3.5   0.5   1.75]]


In [131]:
ba = np.vstack([a,b])
print(ba)

[[ 1.    2.  ]
 [ 1.    2.5 ]
 [ 1.    3.  ]
 [ 1.    3.5 ]
 [ 1.5   2.  ]
 [ 1.5   2.5 ]
 [ 1.5   3.  ]
 [ 1.5   3.5 ]
 [ 2.    2.  ]
 [ 2.    2.5 ]
 [ 2.    3.  ]
 [ 2.    3.5 ]
 [ 2.5   2.  ]
 [ 2.5   2.5 ]
 [ 2.5   3.  ]
 [ 2.5   3.5 ]
 [-1.    1.  ]
 [-1.    1.25]
 [-1.    1.5 ]
 [-1.    1.75]
 [-0.5   1.  ]
 [-0.5   1.25]
 [-0.5   1.5 ]
 [-0.5   1.75]
 [ 0.    1.  ]
 [ 0.    1.25]
 [ 0.    1.5 ]
 [ 0.    1.75]
 [ 0.5   1.  ]
 [ 0.5   1.25]
 [ 0.5   1.5 ]
 [ 0.5   1.75]]


In [132]:
a = np.fromstring('1,2,3,4', sep = ',')
b = np.fromstring('5,6,7,8', sep = ',')

print(np.hstack([a,b]))
print(np.vstack([a,b]))

[1. 2. 3. 4. 5. 6. 7. 8.]
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [133]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Разбиение матрицы на равные части
split_result = np.split(matrix, 3)

# Разбиение матрицы по указанным индексам
split_custom = np.split(matrix, [1,3,2])

print("Разбиение матрицы на равные части:")
for part in split_result:
    print(part)

print("\nРазбиение матрицы по указанным индексам:")
for part in split_custom:
    print(part)

Разбиение матрицы на равные части:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Разбиение матрицы по указанным индексам:
[[1 2 3]]
[[4 5 6]
 [7 8 9]]
[]
[[7 8 9]]


In [134]:
# Создание двух матриц
matrix_a = np.array([[1, 2], [3, 4]])
print(matrix_a)
matrix_b = np.array([[5, 6], [7, 8]])
print(matrix_b)

# Объединение матриц по вертикали
vertical_stack = np.vstack((matrix_a, matrix_b))

# Объединение матриц по горизонтали
horizontal_stack = np.hstack((matrix_a, matrix_b))

print("Объединение матриц по вертикали:")
print(vertical_stack)

print("\nОбъединение матриц по горизонтали:")
print(horizontal_stack)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Объединение матриц по вертикали:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Объединение матриц по горизонтали:
[[1 2 5 6]
 [3 4 7 8]]


In [135]:
arr = np.array([1, 2, 3, 4, 5])
labels = np.array([1,0,1,1,0])

indices = np.array([0, 2, 4, 1, 3]) 

arr_shuffled = arr[indices]

In [136]:
shuffled_indices = np.random.permutation(5)
print(shuffled_indices)

sh_ar = arr[shuffled_indices]
sh_labels = labels[shuffled_indices]

[0 3 1 2 4]


In [137]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
print(a, b)

# Сложение
addition = np.add(a, b)
print("Результат сложения:", addition)

# Вычитание
subtraction = np.subtract(b, a)
print("Результат вычитания:", subtraction)

# Умножение
multiplication = np.multiply(a, b)
print("Результат умножения:", multiplication)

# Деление
division = np.divide(b, a)
print("Результат деления:", division)

# Возведение в степень
exponentiation = np.power(a, 2) # еще можно a**2
print("Результат возведения в степень:", exponentiation)

# Сумма всех элементов
sum_all = np.sum(a)
print("Сумма всех элементов в массиве 'a':", sum_all)

# Среднее значение
mean_value = np.mean(b)
print("Среднее значение всех элементов в массиве 'b':", mean_value)

# Максимальное значение
max_value = np.max(a)
print("Максимальное значение в массиве 'a':", max_value)

# Минимальное значение
min_value = np.min(b)
print("Минимальное значение в массиве 'b':", min_value)

[1 2 3 4 5] [ 6  7  8  9 10]
Результат сложения: [ 7  9 11 13 15]
Результат вычитания: [5 5 5 5 5]
Результат умножения: [ 6 14 24 36 50]
Результат деления: [6.         3.5        2.66666667 2.25       2.        ]
Результат возведения в степень: [ 1  4  9 16 25]
Сумма всех элементов в массиве 'a': 15
Среднее значение всех элементов в массиве 'b': 8.0
Максимальное значение в массиве 'a': 5
Минимальное значение в массиве 'b': 6


In [138]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 2, 3, 4, 1])

# Операторы сравнения
greater = np.greater(a, b)  # Сравнение на больше
print("Результат сравнения на больше:", greater)

greater_equal = np.greater_equal(a, b)  # Сравнение на больше или равно
print("Результат сравнения на больше или равно:", greater_equal)

less = np.less(a, b)  # Сравнение на меньше
print("Результат сравнения на меньше:", less)

less_equal = np.less_equal(a, b)  # Сравнение на меньше или равно
print("Результат сравнения на меньше или равно:", less_equal)

equal = np.equal(a, b)  # Сравнение на равенство
print("Результат сравнения на равенство:", equal)

not_equal = np.not_equal(a, b)  # Сравнение на неравенство
print("Результат сравнения на неравенство:", not_equal)

print("Результат сравнения на any:", np.any(a >5))
print("Результат сравнения на all:", np.all(a >5))
div0 = a/0
print(" делим на 0 ", div0)

#np.array_equal - все соотвт елементы равны

Результат сравнения на больше: [False False False False  True]
Результат сравнения на больше или равно: [False  True  True  True  True]
Результат сравнения на меньше: [ True False False False False]
Результат сравнения на меньше или равно: [ True  True  True  True False]
Результат сравнения на равенство: [False  True  True  True False]
Результат сравнения на неравенство: [ True False False False  True]
Результат сравнения на any: False
Результат сравнения на all: False
 делим на 0  [inf inf inf inf inf]


C:\Users\egors\AppData\Local\Temp\ipykernel_6320\1058744225.py:25: RuntimeWarning: divide by zero encountered in divide
  div0 = a/0


In [139]:
arr = np.array([1, 2, np.nan, 3, np.inf, 4, 5, -np.inf])

# Фильтрация nan и inf значений
filtered_arr = arr[np.isfinite(arr)]

# Вывод отфильтрованного массива
print("Массив без nan и inf значений:", filtered_arr)

Массив без nan и inf значений: [1. 2. 3. 4. 5.]


In [140]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
print(matrix_a)
print(matrix_b)

matrix_product = np.dot(matrix_a, matrix_b)
print("Произведение двух матриц:")
print(matrix_product)

# Произведение векторов
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

vector_product = np.dot(vector_a, vector_b)
print("Скалярное произведение векторов:", vector_product)

outer_product = np.outer(vector_a, vector_b)
print("внешнее произведение векторов:", outer_product)

# Вычисление определителя матрицы
det_matrix_a = np.linalg.det(matrix_a)
print("Определитель матрицы:")
print(det_matrix_a)

# Вычисление обратной матрицы
inverse_matrix_a = np.linalg.inv(matrix_a)
print("Обратная матрица:")
print(inverse_matrix_a)

# Вычисление собственных значений и собственных векторов
eigen_values, eigen_vectors = np.linalg.eig(matrix_a)
print("Собственные значения:")
print(eigen_values)
print("Собственные векторы:")
print(eigen_vectors)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Произведение двух матриц:
[[19 22]
 [43 50]]
Скалярное произведение векторов: 32
внешнее произведение векторов: [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Определитель матрицы:
-2.0000000000000004
Обратная матрица:
[[-2.   1. ]
 [ 1.5 -0.5]]
Собственные значения:
[-0.37228132  5.37228132]
Собственные векторы:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [141]:
# Решение системы линейных уравнений:

A = np.array([[3, 1], [1, 2]])

B = np.array([9, 8])

solution = np.linalg.solve(A, B)

print( solution)

[2. 3.]
